# Generated by Django 5.1.3 on 2024-11-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_accout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accout',
            new_name='Account',
        ),
    ]
