# Generated by Django 5.0.4 on 2024-04-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'BackEnd-Dev'), (2, 'FrontEnd-Dev'), (3, 'QA'), (4, 'DevOps'), (5, 'Team Lead')]),
        ),
    ]
