# Generated by Django 5.0.4 on 2024-04-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('SoftUni', 'SoftUni'), ('Google', 'Google'), ('Microsoft', 'Microsoft')], default='SoftUni', max_length=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'BackEnd-Dev'), (2, 'FrontEnd-Dev'), (3, 'QA'), (4, 'DevOps'), (5, 'Team Lead')], default=1),
        ),
    ]
