# Generated by Django 5.0.4 on 2024-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_company_alter_employee_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('year', models.DateField()),
                ('engine', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric')], max_length=10)),
                ('category', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('price', models.FloatField()),
            ],
        ),
    ]
