# Generated by Django 5.0.4 on 2024-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('deadline', models.DateField(null=True)),
                ('employees', models.ManyToManyField(to='employees.employee')),
            ],
        ),
    ]
