# Generated by Django 5.0.4 on 2024-05-02 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='dealership_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicles.dealership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='dealership_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='vehicles.dealership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='dealership_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='vehicles.dealership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='dealership_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='vehicles.dealership'),
            preserve_default=False,
        ),
    ]
