# Generated by Django 4.2.13 on 2024-06-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Sofia', 'Sofia'), ('Varna', 'Varna'), ('Plovdiv', 'Plovdiv'), ('Pleven', 'Pleven')], default='Sofia', max_length=7)),
                ('users_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='job_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms_app.department'),
            preserve_default=False,
        ),
    ]
