# Generated by Django 5.0.6 on 2024-06-28 08:08

import django.core.validators
import regular_exam_02.web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Username:')),
                ('first_name', models.CharField(max_length=20, validators=[regular_exam_02.web_app.models.validate_person_name], verbose_name='First Name:')),
                ('last_name', models.CharField(max_length=20, validators=[regular_exam_02.web_app.models.validate_person_name], verbose_name='Last Name:')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile Picture URL:')),
            ],
        ),
    ]
