# Generated by Django 5.0.6 on 2024-06-28 09:34

import django.core.validators
import regular_exam_02.web_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), regular_exam_02.web_app.validators.validate_plant_name], verbose_name='Plant name:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Username:'),
        ),
    ]
