# Generated by Django 5.0.4 on 2024-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_first_name_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='egn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
