# Generated by Django 5.0.4 on 2024-04-30 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.department'),
        ),
    ]
