# Generated by Django 5.0.4 on 2024-04-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
